import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { runAI, loadPrompt } from '../lib/ai.js';
import { bold, dim, green, red } from '../lib/ui.js';
import { parseOas } from '../lib/oas-parse.js';
import { loadOas } from '../lib/oas-auth.js';
import { readSpecForUpload } from '../lib/oas-bundle.js';
import { safeWriteFileSync, safeMkdirSync } from '../lib/pathGuard.js';

/**
 * Where a spec comes from, and how to get it again.
 *
 * `npx restless init` records provenance on each API entry as `oasSource`, and
 * `npx restless update` is the reason that matters: "refresh my spec" means
 * something completely different depending on how the spec got here. A URL
 * gets re-fetched (no AI, no code reading). A file the user maintains gets
 * re-read and re-validated, because it is already the source of truth and
 * nothing of ours should regenerate it. Only the AI and native-generator
 * kinds involve looking at the routes again.
 *
 * These primitives live here rather than in `steps/generate-oas.js` so both
 * flows share one implementation - otherwise the update path would grow a
 * second, subtly different copy of "fetch a spec and check it parses".
 */

/**
 * Everything that varies by `oasSource.kind`, in one table.
 *
 * This used to be five things in four files: a phrasing switch, a
 * pick-to-source switch, two Sets partitioning the kinds by capability, an
 * if/else chain building the action list, and a hand-inlined
 * `kind === 'describe' || kind === 'native'` in the entry point. They all
 * answered questions about the same seven values and drifted independently.
 *
 * Per kind:
 *  - `phrase`      how to say where the spec came from, in one short line
 *  - `autoCheck`   is there a source to go back to, so `update` can check it
 *                  before asking anything
 *  - `needsAgent`  does re-deriving it mean running an agent over the code
 *  - `strategy`    how a refresh reproduces it (see REFRESH_STRATEGIES in
 *                  steps/update-oas.js, which a test binds to this list)
 *  - `action`      the primary action `update` offers, or null when the
 *                  recorded source has lost the detail it would need
 *  - `fromPick`    what to record when init's source picker chooses this kind
 */
export const OAS_SOURCES = {
  ai: {
    // Our model read the routes and wrote it.
    phrase: () => 'generated with AI',
    // No source to return to. The spec was authored by reading the whole
    // codebase, so "check for changes" means doing that again from scratch -
    // a decision, not a status check.
    autoCheck: false,
    needsAgent: true,
    strategy: 'generate',
    action: () => null, // falls through to the shared regenerate action
    fromPick: () => ({ kind: 'ai' }),
  },
  native: {
    // The framework's own generator emitted it.
    phrase: (src) => (src.framework ? `generated by ${src.framework}` : 'generated by your framework'),
    autoCheck: true,
    needsAgent: true,
    strategy: 'generate-native',
    action: (entry, src) => ({
      key: 'regenerate-native',
      label: `Regenerate with ${src.framework || 'your framework'}`,
      hint: "Uses the framework's own generator, then fills any gaps from the routes.",
    }),
    fromPick: ({ framework } = {}) => ({ kind: 'native', framework: framework || null }),
  },
  found: {
    // Already in the repo; we point at it and never write it.
    phrase: (src) => (src.path ? `already in your repo at ${src.path}` : 'already in your repo'),
    autoCheck: true,
    needsAgent: false,
    strategy: 'reread',
    action: (entry) => ({
      key: 'revalidate',
      label: `Re-check ${entry.oasFile}`,
      hint: 'Your file is the source of truth: we only validate it and push it.',
    }),
    fromPick: ({ existingOasFile } = {}) => ({ kind: 'found', path: existingOasFile || null }),
  },
  file: {
    // The user pointed us at a path.
    phrase: (src) => (src.input ? `from ${src.input}` : 'from a file you provided'),
    autoCheck: true,
    needsAgent: false,
    strategy: 'reread',
    action: (entry) => ({
      key: 'revalidate',
      label: `Re-check ${entry.oasFile}`,
      hint: 'Your file is the source of truth: we only validate it and push it.',
    }),
  },
  url: {
    // Fetched from a URL.
    phrase: (src) => (src.url ? `fetched from ${src.url}` : 'fetched from a URL'),
    autoCheck: true,
    needsAgent: false,
    strategy: 'fetch',
    action: (entry, src) => (src.url
      ? {
        key: 'refetch',
        label: `Re-fetch from ${src.url}`,
        hint: 'Downloads it again and shows what changed. No AI, no code reading.',
      }
      : null),
  },
  describe: {
    // Located by AI from a plain-English description.
    // Deliberately NOT `src.summary`. That is model-written prose recorded so
    // we can reproduce the spec later, and it runs to whole paragraphs
    // describing internals ("generated by running buildOpenApiSpec() from
    // src/lib/... via tsx, with server URL ..."). Every caller of this renders
    // one short line - a picker hint, a step header, a status line - so the
    // summary belongs in the settings file, not on screen.
    phrase: () => 'from the location you described',
    autoCheck: true,
    needsAgent: true,
    strategy: 'locate',
    action: (entry, src) => (src.summary
      ? {
        key: 'replay',
        // Generic on purpose, for the same reason `phrase` is.
        label: 'Get the latest spec',
        hint: 'Repeats however this spec was produced last time.',
      }
      : null),
  },
  combined: {
    // Several specs the user maintains, combined into the one file we own. Only the inputs are theirs.
    phrase: (src) => `combined from ${src.paths?.length || 'several'} specs`,
    autoCheck: true,
    needsAgent: false,
    strategy: 'combine',
    action: (entry, src) => (src.paths?.length
      ? {
        key: 'recombine',
        label: `Re-combine your ${src.paths.length} specs`,
        hint: 'Re-reads each file and rebuilds the combined spec. Your files are left alone.',
      }
      : null),
    fromPick: ({ paths } = {}) => ({ kind: 'combined', paths: paths || [] }),
  },
  agent: {
    // Written by a coding agent via `npx restless register`.
    phrase: () => 'written by your coding agent',
    autoCheck: false,
    needsAgent: true,
    strategy: 'generate',
    action: () => null,
  },
};

/** Every `oasSource.kind` the CLI writes. */
export const OAS_SOURCE_KINDS = Object.keys(OAS_SOURCES);

/**
 * The facets for a kind, with a safe default for a settings file written by a
 * newer CLI (or hand-edited). An unknown kind is treated the way `ai` is: no
 * source to return to, so nothing is checked automatically and refreshing is
 * an explicit choice.
 */
export function oasSourceFacets(kind) {
  return OAS_SOURCES[kind] || {
    phrase: () => 'from your last setup',
    autoCheck: false,
    needsAgent: true,
    strategy: 'generate',
    action: () => null,
  };
}

/**
 * Kinds `update` re-derives on its own, before asking anything: the ones with
 * a source to go back to. A URL can be re-fetched, a file the developer
 * maintains can be re-read, a recorded command can be run again, and a
 * framework generator can be re-run.
 */
export function autoCheckKinds() {
  return new Set(OAS_SOURCE_KINDS.filter((k) => OAS_SOURCES[k].autoCheck));
}

/**
 * The subset that needs no agent. `--status` is the cheap probe an agent calls
 * before deciding what to do, and having it spawn a second agent to answer
 * would defeat the point.
 */
export function noAgentKinds() {
  return new Set(OAS_SOURCE_KINDS.filter((k) => OAS_SOURCES[k].autoCheck && !OAS_SOURCES[k].needsAgent));
}

/**
 * The one path we own and are allowed to overwrite. A spec that came from the
 * user (`found` / `file`) lives wherever they keep it, and regenerating must
 * never clobber that - it writes here instead and re-points `oasFile`.
 */
export const MANAGED_OAS_FILE = '.restless/openapi.json';

export const HTTP_METHODS = new Set([
  'get',
  'put',
  'post',
  'delete',
  'options',
  'head',
  'patch',
  'trace',
]);

/** Is this spec one we generated into `.restless/`, or the user's own file? */
export function isManagedSpec(oasFile) {
  if (!oasFile) return false;
  return !path.relative('.restless', oasFile).startsWith('..');
}

/**
 * Human-readable account of how a spec was sourced, for the reuse-on-rerun
 * note and for `update`'s per-kind action labels. One short line, always.
 */
export function describeOasSource(src) {
  return oasSourceFacets(src?.kind).phrase(src || {});
}

/**
 * Which `oasSource` a source-picker choice should record. Only the kinds
 * init's picker can choose have a `fromPick`; the others record their own
 * provenance where they resolve it (a URL knows its URL), so this returns null
 * rather than guessing.
 */
export function oasSourceForPick(picked, opts = {}) {
  return OAS_SOURCES[picked]?.fromPick?.(opts) ?? null;
}

// Collapse a path to a shape we can compare across sources: parameter names
// don't matter for coverage (`/users/{id}` == `/users/{userId}` == `/users/:id`),
// and a trailing slash is not a distinct route.
export function normalizeApiPath(p) {
  const collapsed = p
    .replace(/\{[^}]+\}/g, '{}') // {id} / {userId} -> {}
    .replace(/:[^/]+/g, '{}') // :id -> {}
    .replace(/\/+$/, ''); // drop trailing slash
  return collapsed === '' ? '/' : collapsed;
}

/**
 * Every operation in a parsed spec, as `METHOD /normalized/path` strings.
 * Normalizing the path means a rename of `{id}` to `{userId}` doesn't read as
 * "one route removed, one added" in a diff.
 */
export function operationSet(oas) {
  const out = new Set();
  for (const [p, ops] of Object.entries(oas?.paths || {})) {
    if (!ops || typeof ops !== 'object') continue;
    for (const m of Object.keys(ops)) {
      if (HTTP_METHODS.has(m.toLowerCase())) {
        out.add(`${m.toUpperCase()} ${normalizeApiPath(p)}`);
      }
    }
  }
  return out;
}

/** Key order is not meaning in JSON, so compare a canonical form. Otherwise a
 *  generator that emits keys in a different order reads as a change.
 *
 *  MIRRORED in the dashboard at `src/lib/oasSync.ts`. The two implementations
 *  must produce identical output byte for byte, because `oasHash` is compared
 *  across the wire to decide whether the dashboard's spec matches the local
 *  one. Both repos pin it with the same fixture hash. */
export function stableStringify(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value) ?? 'null';
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  const keys = Object.keys(value).sort();
  return `{${keys.map((k) => `${JSON.stringify(k)}:${stableStringify(value[k])}`).join(',')}}`;
}

/** Every operation as `METHOD /normalized/path` -> canonical body. */
function operationBodies(oas) {
  const out = new Map();
  for (const [p, ops] of Object.entries(oas?.paths || {})) {
    if (!ops || typeof ops !== 'object') continue;
    for (const [m, op] of Object.entries(ops)) {
      if (!HTTP_METHODS.has(m.toLowerCase())) continue;
      out.set(`${m.toUpperCase()} ${normalizeApiPath(p)}`, stableStringify(op));
    }
  }
  return out;
}

/**
 * What changed between two parsed specs, at the level someone can act on.
 *
 * Added and removed endpoints are the headline. But a regenerated spec very
 * often has exactly the same endpoints with different descriptions, schemas or
 * examples - which matters, because those are what the docs and the AI chat
 * actually serve. Reporting only added/removed left the honest-but-useless
 * "the spec changed, but the same endpoints are in it", so `modified` counts
 * the shared operations whose contents differ, and `metadataOnly` says the
 * difference was entirely outside the operations (servers, info, components).
 */
export function diffOperations(beforeOas, afterOas) {
  const before = operationBodies(beforeOas);
  const after = operationBodies(afterOas);
  const added = [...after.keys()].filter((op) => !before.has(op)).sort();
  const removed = [...before.keys()].filter((op) => !after.has(op)).sort();
  const modified = [...after.keys()]
    .filter((op) => before.has(op) && before.get(op) !== after.get(op))
    .sort();
  // Which top-level sections other than `paths` differ. Without this the
  // no-operation-changed case can only guess ("the server URL, version or
  // components moved"), when naming the section is both cheap and the whole
  // answer - a regenerated spec whose only difference is `info.title` should
  // say so.
  const sections = [...new Set([...Object.keys(beforeOas || {}), ...Object.keys(afterOas || {})])]
    .filter((k) => k !== 'paths')
    .filter((k) => stableStringify(beforeOas?.[k]) !== stableStringify(afterOas?.[k]))
    .sort();

  return {
    added,
    removed,
    modified,
    changedSections: sections,
    // `changed` stays "did the endpoint surface move", which is what the
    // removal warning and the coverage checks key off.
    changed: added.length > 0 || removed.length > 0,
    // Something differed, but not in any operation.
    metadataOnly: added.length === 0 && removed.length === 0 && modified.length === 0,
  };
}

/**
 * Count operations in a spec on disk, so a confirm screen can say "23
 * endpoints" - the fastest way for someone to tell whether a spec is the one
 * they meant. Returns null when the file won't parse.
 */
export function countOasEndpoints(absPath) {
  try {
    const oas = loadOas(absPath);
    // `loadOas` returns null rather than throwing on a parse failure, so
    // without this an unreadable spec counted as 0 operations instead of
    // "can't read it". Three callers key off null to mean exactly that:
    // `rememberedApis` drops such a spec rather than offering it, the
    // revalidate action reports it, and the up-front check fails soft.
    if (oas === null || typeof oas !== 'object') return null;
    let n = 0;
    for (const ops of Object.values(oas?.paths || {})) {
      for (const method of Object.keys(ops || {})) {
        if (HTTP_METHODS.has(method.toLowerCase())) n++;
      }
    }
    return n;
  } catch {
    return null;
  }
}

/**
 * Fingerprint of a spec's CONTENT, recorded when we push.
 *
 * Canonical, not byte-level, and that distinction is load-bearing twice over:
 *
 *  - Locally, it means reformatting a spec (a generator changing its
 *    indentation or key order) doesn't read as a change and doesn't prompt a
 *    pointless push. A real 560-byte reformat turned out to be 11 bytes of
 *    actual difference.
 *  - Across the wire, it makes the hash comparable at all. The dashboard
 *    parses an uploaded spec and stores the object, discarding the raw text,
 *    so it can never reproduce the bytes we hashed - but it can canonicalize
 *    the same way. That is how `update` can tell whether the dashboard's spec
 *    matches the local one without downloading it.
 *
 * A hash answers "did it change", not "what changed", which is why
 * `oasOperationCount` is stored alongside it and why the dashboard also hands
 * back its operation list.
 */
export function canonicalOasHash(oas) {
  if (!oas || typeof oas !== 'object') return null;
  return crypto.createHash('sha256').update(stableStringify(oas)).digest('hex');
}

/** Canonical hash of a spec on disk, or null if it won't parse. */
export function hashOasFile(absPath) {
  try {
    return canonicalOasHash(loadOas(absPath));
  } catch {
    return null;
  }
}

/** The fingerprint pair to record on an entry after a successful push. */
export function fingerprintSpec(absPath) {
  const oasHash = hashOasFile(absPath);
  if (!oasHash) return null;
  return { oasHash, oasOperationCount: countOasEndpoints(absPath) ?? 0 };
}

const MAX_OAS_FIX_ATTEMPTS = 2;

/**
 * Re-indent a spec the model just emitted compact.
 *
 * Generation is output-token-bound: a profiled run emitted a 39,817-byte
 * pretty-printed spec at ~93 tokens/sec, taking 118.6 seconds in a single
 * `Write` - a quarter of the whole `init`. The same document minifies to
 * 26,768 bytes, so a third of those tokens were indentation the model was
 * generating one space at a time.
 *
 * So the prompt asks for compact JSON and the indenting happens here, for
 * free. The committed file looks exactly as it did before; only the tokens
 * are gone.
 *
 * JSON only, and only when asked (`reindent`). A YAML spec has its own
 * formatting conventions, and every other caller of `validateAndFixOas` is
 * validating a file the USER brought - reformatting one of those would put
 * a spurious whole-file diff in their working tree.
 */
function reindentJsonSpec(oasFullPath, raw, parsed) {
  try {
    const pretty = `${JSON.stringify(parsed, null, 2)}\n`;
    // Nothing to do when the model ignored the instruction and pretty-printed
    // anyway - and skipping the write keeps the mtime honest.
    if (pretty === raw) return false;
    safeWriteFileSync(oasFullPath, pretty);
    return true;
  } catch {
    // The spec already parsed, so it is valid and usable as-is. A failed
    // cosmetic rewrite must never fail the run.
    return false;
  }
}

// Read the file we just wrote and parse it the same way the server will. If
// it doesn't parse, hand the error back to the LLM and ask it to fix the file
// in place. Retries up to MAX_OAS_FIX_ATTEMPTS times.
//
// `reindent` pretty-prints a valid JSON spec on the way out. Only the
// generation path passes it - see `reindentJsonSpec`.
export async function validateAndFixOas({ oasFullPath, packageDir, setSpinner, reindent = false }) {
  for (let attempt = 0; attempt <= MAX_OAS_FIX_ATTEMPTS; attempt++) {
    let raw;
    try {
      raw = fs.readFileSync(oasFullPath, 'utf8');
    } catch (err) {
      return { ok: false, error: `Could not read ${oasFullPath}: ${err.message}` };
    }
    const format = oasFullPath.endsWith('.json') ? 'json' : 'yaml';
    const result = parseOas(raw, format);
    if (result.ok) {
      if (reindent && format === 'json') reindentJsonSpec(oasFullPath, raw, result.oas);
      return { ok: true };
    }

    if (attempt === MAX_OAS_FIX_ATTEMPTS) {
      return { ok: false, error: result.error };
    }

    setSpinner('Fixing OpenAPI spec');
    const fixPrompt = loadPrompt('fix-oas', {
      oasFile: oasFullPath,
      parseError: result.error,
    });
    await runAI(fixPrompt, packageDir, { setSpinner, label: 'fix-oas' });
  }
  return { ok: false, error: 'Exhausted fix attempts' };
}

export function isStrictJson(raw) {
  try {
    JSON.parse(raw);
    return true;
  } catch {
    return false;
  }
}

/**
 * Fetch a spec from a URL once, validate it parses (same parser the server
 * uses), and save it as `openapi.<ext>` inside `destDir`.
 *
 * Returns a result rather than printing and handing back a bare path. Two
 * reasons, both of which used to be bugs: a scratch download reports a path
 * the developer never chose and can't act on, so the caller has to know
 * whether to show it; and a failure carried its reason to the terminal only,
 * so `--json` callers - agents, the audience that most needs the reason - got
 * a generic "couldn't use that as a spec" with the real error swallowed.
 *
 * `destDir` is a directory, not a filename base: `update` stages a refresh
 * into its own directory so nothing it downloads can land on the spec the
 * developer is still deciding whether to replace.
 */
export async function fetchOasFromUrl({ url, rootDir, destDir, setSpinner = () => {} }) {
  setSpinner({ phase: 'Fetching spec', detail: url });
  let raw;
  try {
    const res = await fetch(url);
    if (!res.ok) {
      setSpinner('');
      return { ok: false, error: `${url} returned ${res.status}.` };
    }
    raw = await res.text();
  } catch (err) {
    setSpinner('');
    return { ok: false, error: `Couldn't fetch ${url}: ${err.message}` };
  }
  setSpinner('');

  // Detect JSON vs YAML so we save with the right extension (validateAndFixOas
  // and the server both key off it). Try strict JSON first, then YAML.
  let format = 'json';
  let parsed = parseOas(raw, 'json');
  if (!parsed.ok || !isStrictJson(raw)) {
    const asYaml = parseOas(raw, 'yaml');
    if (asYaml.ok && !isStrictJson(raw)) {
      parsed = asYaml;
      format = 'yaml';
    }
  }
  if (!parsed.ok) {
    return {
      ok: false,
      error: "That URL didn't return a valid OpenAPI spec.",
      detail: parsed.error,
    };
  }

  const dest = path.join(destDir, `openapi${format === 'yaml' ? '.yaml' : '.json'}`);
  if (!fs.existsSync(destDir)) safeMkdirSync(destDir, { recursive: true });
  safeWriteFileSync(dest, raw);
  return { ok: true, oasFile: path.relative(rootDir, dest), outcome: 'downloaded' };
}

/**
 * Adopt an OAS file already on disk. A file inside the repo is pointed at, not
 * copied - it is already the source of truth and ours to read, never to write.
 * One outside the repo is copied into `destDir` so it ships with the code.
 */
export function adoptOasFile({ absPath, rootDir, destDir }) {
  const raw = (() => {
    try { return fs.readFileSync(absPath, 'utf8'); } catch { return null; }
  })();
  const rel = path.relative(rootDir, absPath);
  // Name it the way the developer would: repo-relative inside the repo,
  // absolute outside it. `path.relative` to a file a few directories up
  // produces `../../../../../../tmp/spec.json`, which is technically correct
  // and unreadable.
  const shown = rel.startsWith('..') ? absPath : rel;
  if (raw === null) return { ok: false, error: `Couldn't read ${shown}.` };

  const format = absPath.endsWith('.json') ? 'json' : 'yaml';
  const parsed = parseOas(raw, format);
  if (!parsed.ok) {
    return {
      ok: false,
      error: `${shown} didn't parse as an OpenAPI spec.`,
      detail: parsed.error,
    };
  }

  // Caught now rather than at claim time, when the upload would first try to resolve them.
  const upload = readSpecForUpload(absPath, shown);
  if (!upload.ok) return { ok: false, error: upload.error, detail: upload.detail };

  if (!rel.startsWith('..')) return { ok: true, oasFile: rel, outcome: 'pointed' };

  // Outside the repo - copy in so it lives with the codebase. A split spec is
  // copied bundled, since its fragments would not come with it.
  if (!fs.existsSync(destDir)) safeMkdirSync(destDir, { recursive: true });
  const ext = upload.bundled ? '.json' : (path.extname(absPath) || '.yaml');
  const dest = path.join(destDir, `openapi${ext}`);
  try {
    if (upload.bundled) safeWriteFileSync(dest, `${JSON.stringify(JSON.parse(upload.raw), null, 2)}\n`);
    else fs.copyFileSync(absPath, dest);
  } catch (err) {
    return { ok: false, error: `Couldn't copy ${shown}: ${err.message}` };
  }
  return { ok: true, oasFile: path.relative(rootDir, dest), outcome: 'copied' };
}

/**
 * How to say what a spec-acquisition result did. Lives here, next to the
 * functions that produce the shape, so `init` and `update` narrate an adopted
 * spec identically instead of each writing their own version.
 *
 * A staged result says nothing: the path is scratch bookkeeping, and the
 * caller reports the outcome that actually matters.
 */
export function describeSpecOutcome(res, { staged = false } = {}) {
  if (!res.ok) {
    return ['', `  ${red('✗')} ${res.error}`, ...(res.detail ? [`  ${dim(res.detail)}`] : [])];
  }
  if (staged) return [];
  const file = bold(res.oasFile);
  if (res.outcome === 'downloaded') return ['', `  ${green('✓')} Downloaded to ${file}.`];
  if (res.outcome === 'copied') return ['', `  ${green('✓')} Copied to ${file} so it lives with your code.`];
  return ['', `  ${green('✓')} Using the file at ${file}.`];
}
